#!/bin/sh

tag="all"

mkdir -p ./root/Gen/${tag}

# Erel will be generated by irun input.

for irun in {01..07}; do
    root -b -q './macros/17Bnn/GenInput_17Bnn.cc++('$irun',"'${tag}'")'
done

wait

echo 'Simulation input generated in a range of 0 to '$irun' MeV'
