/control/execute geometry/geom_dayone_D.mac
/samurai/geometry/Update
/action/file/OverWrite y
/action/file/RunName Sim17Bnn07_20mrad
/action/file/SaveDirectory root/Sim/20mrad
/action/gun/Type Tree
/action/gun/tree/InputFileName root/Gen/20mrad/17BnnInp07_20mrad.root
/action/gun/tree/TreeName tree
/action/data/NEBULA/StoreSteps false
/action/data/NEBULA/Resolution false
/action/gun/tree/beamOn 1000000
